---

- name: Ensure HAProxy socket directory exists
  file:
    path: /run/haproxy
    state: directory
    mode: "0755"
  when: ansible_os_family != 'Debian'

- name: Ensure HAProxy is installed.
  package: 
    name: haproxy
    state: present
    update_cache: true

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0640
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
  service: 
    name: haproxy
    state: started
    enabled: true