---
- name: Converge
  hosts: all
  tasks:
    - name: "Include k3s-haproxy"
      include_role:
        name: "ansible-role-k3s-haproxy"
      vars:
        haproxy_frontend:
          - name: memcached
            bind:
              - listen: '127.0.0.1:11211'
            mode: tcp
            option:
              - dontlog-normal
            default_backend: memcached-servers

        haproxy_backend:
          - name: memcached-servers
            mode: tcp
            option:
              - dontlog-normal
            balance: roundrobin
            server:
              - name: memcached-01
                listen: '127.0.1.1:11211'
                param:
                  - check
              - name: memcached-02
                listen: '127.0.2.1:11211'
                param:
                  - check
                  - backup